using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO.Pipelines;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shared.CoreOne.Models.StaticData
{
	public static class MenuCodeData
	{
		public const int Requests = 1;
		public const int ApprovalsSteps = 2;
		public const int DocumentsApprovals = 3;
		public const int ImportBasicData = 4;
		public const int MenuEncoding = 5;
		public const int ApplicationSettings = 6;
		public const int Countries = 7;
		public const int States = 8;
		public const int Cities = 9;
		public const int Districts = 10;
		public const int Business = 11;
		public const int Branches = 12;
		public const int Stores = 13;
		public const int Supplier = 14;
		public const int Client = 15;
		public const int Seller = 16;
		public const int Bank = 17;
		public const int NotesIdentifiers = 18;
		public const int SellerCommissionNames = 19;
		public const int InvoiceExpenseTypes = 20;
		public const int ShipmentTypes = 21;
		public const int ShippingStatusTypes = 22;
		public const int SellersCommissionMethods = 23;
		public const int Taxes = 24;
		public const int PaymentMethods = 25;
		public const int Currencies = 26;
		public const int CurrenciesRates = 27;
		public const int Item = 28;
		public const int ItemPackages = 29;
		public const int ItemsCategory = 30;
		public const int Vendors = 31;
		public const int ItemAttributes = 32;
		public const int OpenBalance = 33;
		public const int CurrentBalance = 34;
		public const int ItemCost = 35;
		public const int StockTakingOpenBalance = 36;
		public const int ApprovalStockTakingAsOpenBalance = 37;
		public const int StockTakingCurrentBalance = 38;
		public const int ApprovalStockTakingAsCurrentBalance = 39;
		public const int InventoryIn = 40;
		public const int InventoryOut = 41;
		public const int InternalTransferItems = 42;
		public const int InternalReceiveItems = 43;
		public const int Account = 44;
		public const int JournalEntry = 45;
		public const int ReceiptVoucher = 46;
		public const int PaymentVoucher = 47;
		public const int CostCenter = 48;
		public const int ProductRequest = 49;
		public const int ProductRequestPrice = 50;
		public const int SupplierQuotation = 51;
		public const int CashPurchaseInvoice = 52;
		public const int CreditPurchaseInvoice = 53;
		public const int CashPurchaseInvoiceReturn = 54;
		public const int CreditPurchaseInvoiceReturn = 55;
		public const int PurchaseOrder = 56;
		public const int ReceiptStatement = 57;
		public const int ReceiptStatementReturn = 58;
		public const int PurchaseInvoiceInterim = 59;
		public const int PurchaseInvoiceOnTheWayCash = 60;
		public const int PurchaseInvoiceOnTheWayCredit = 61;
		public const int ReceiptFromPurchaseInvoiceOnTheWay = 62;
		public const int ReceiptFromPurchaseInvoiceOnTheWayReturn = 63;
		public const int PurchaseInvoiceReturnOnTheWay = 64;
		public const int ReturnFromPurchaseInvoice = 65;
		public const int PurchaseInvoiceReturn = 66;
		public const int SupplierDebitMemo = 67;
		public const int SupplierCreditMemo = 68;
		public const int ClientPriceRequest = 69;
		public const int ClientQuotation = 70;
		public const int ClientQuotationApproval = 71;
		public const int CashSalesInvoice = 72;
		public const int CreditSalesInvoice = 73;
		public const int CashSalesInvoiceReturn = 74;
		public const int CreditSalesInvoiceReturn = 75;
		public const int ProformaInvoice = 76;
		public const int StockOutFromProformaInvoice = 77;
		public const int StockOutReturnFromStockOut = 78;
		public const int SalesInvoiceInterim = 79;
		public const int CashReservationInvoice = 80;
		public const int CreditReservationInvoice = 81;
		public const int StockOutFromReservation = 82;
		public const int StockOutReturnFromReservation = 83;
		public const int ReservationInvoiceCloseOut = 84;
		public const int StockOutReturnFromInvoice = 85;
		public const int SalesInvoiceReturn = 86;
		public const int ClientDebitMemo = 87;
		public const int ClientCreditMemo = 88;
		public const int DisassembleItemPackages = 89;
		public const int DisassembleItemPackagesStatement = 90;


        public const int FixedAsset = 158;
        public const int FixedAssetMovement = 159;
        public const int FixedAssetAddition = 160;
		public const int FixedAssetExclusion = 161;
		public const int FixedAssetDepreciation = 162;
		//public const int FixedAssetType = 500;
		//public const int FixedAssetDetail = 500;
    }

	public static class DocumentReferenceData
	{
		public const string Approval = "AP-";
		public const string JournalEntry = "JE-";
		public const string ReceiptVoucher = "RV-";
		public const string PaymentVoucher = "PV-";
		public const string StockTaking = "STCB-";
		public const string StockTakingOpenBalance = "STOB-";
		public const string CarryOver = "COCB-";
		public const string CarryOverOpenBalance = "COOB-";
		public const string InventoryIn = "VI-";
		public const string InventoryOut = "VO-";
		public const string InternalTransfer = "IT-";
		public const string InternalTransferReceive = "ITR-";
		public const string ProductRequest = "PR-";
		public const string ProductRequestPrice = "PRP-";
		public const string SupplierQuotation = "SQ-";
		public const string PurchaseOrder = "PO-";
		public const string ReceiptStatement = "RST-";
		public const string ReceiptFromPurchaseInvoiceOnTheWay = "RPIOTW-";
		public const string ReceiptStatementReturn = "RSTR-";
		public const string ReceiptFromPurchaseInvoiceOnTheWayReturn = "RPIOTWR-";
		public const string CashPurchaseInvoice = "CSPI-";
		public const string CreditPurchaseInvoice = "CRPI-";
		public const string PurchaseInvoiceInterim = "PII-";
		public const string PurchaseInvoiceOnTheWayCash = "PIOTWCS-";
		public const string PurchaseInvoiceOnTheWayCredit = "PIOTWCR-";
		public const string ReturnFromPurchaseInvoice = "RPI-";
		public const string CashPurchaseInvoiceReturn = "CSPIR-";
		public const string CreditPurchaseInvoiceReturn = "CRPIR-";
		public const string PurchaseInvoiceReturn = "PIR-";
		public const string PurchaseInvoiceReturnOnTheWay = "PIROTW-";
		public const string SupplierDebitMemo = "SDM-";
		public const string SupplierCreditMemo = "SCM-";
        public const string ClientPriceRequest = "CPR-";
        public const string ClientQuotation = "CQ-";
        public const string ClientQuotationApproval = "CQA-";
        public const string ProformaInvoice = "PFI-";
        public const string StockOutFromProformaInvoice = "SOPFI-";
        public const string StockOutReturnFromStockOut = "SORSO-";
        public const string SalesInvoiceInterim = "SII-";
		public const string CreditSalesInvoice = "CRSI-";
		public const string CashSalesInvoice = "CSSI-";
		public const string CreditReservationInvoice = "CRRI-";
		public const string CashReservationInvoice = "CSRI-";
		public const string CashSalesInvoiceReturn = "CSSIR-";
		public const string CreditSalesInvoiceReturn = "CRSIR-";
		public const string ReservationInvoiceCloseOut = "RICO-";
		public const string SalesInvoiceReturn = "SIR-";
		public const string StockOutFromReservation = "SOSI-";
        public const string StockOutReturnFromReservation = "SORISO-";
        public const string StockOutReturnFromSalesInvoice = "SORSI-";
        public const string ClientDebitMemo = "CDM-";
        public const string ClientCreditMemo = "CCM-";
		public const string FixedAssetVoucher = "FV-";
    }
}
